
import {
  DataUsageOutlined,
  EditOutlined,
  ManageAccountsOutlined,
  PeopleAltOutlined,
  Settings,
} from "@mui/icons-material";
import { title } from "process";

export const NAVDATA = [
  {
    icon: ManageAccountsOutlined,
    path: "/",
    title: 'Admins'
  },
  {
    icon: PeopleAltOutlined,
    path: "/users",
    title: 'member'
  },
  {
    icon: EditOutlined,
    path: "/safety-report",
    title: 'project'
  },
  {
    icon: DataUsageOutlined,
    path: "/analytics",
    title: 'service'
  },
  {
    icon: DataUsageOutlined,
    path: "/footer",
    title: 'Conatct'
  },
  {
    icon: Settings,
    path: "/settings",
    title: 'Setting'
  },
];

export const PERMISSON_DATA = [
  "All",

  "Manage Users Account",

  "View Users Account",

  "Manage Safety Reports",

  "View Safety Reports",
  "View Analytics & Statistics",
];

export const REPORT_TABLE_DATA = [

  // { label: "COMPANY NAME", field: "companyName" },
  { label: "USER NAME", field: "userName" },
  { label: "SUBJECT", field: "details" },
  { label: "CATEGORY", field: "reason" },
  // { label: "CONTENT", field: "content" },
  { label: "STATUS", field: "status" },
]
// rows: [
//   {
//     companyName: "Coral Design",
//     userName: "Lance Stroll",
//     subject: "I found out he was not part",
//     category: "Misuse",
//     content: "User Profile",
//     status: "Open",
//   },
//   ...Array(7).fill({
//     companyName: "Coral Design",
//     userName: "Lance Stroll",
//     subject: "I found out he was not part",
//     category: "Unrecognized User",
//     content: "Comment",
//     status: "New",
//   }),
// ],

// export const USER_TABLE_DATA_COLUMNS = [
//   { label: "Profile", field: `firstName ` },
//   { label: "Gender", field: "gender" },
//   { label: "Age", field: "dateOfBirth" },
//   { label: "Marital Status", field: "maritalStatus" },
//   { label: "Subscription", field: "subscription" },
//   { label: "Location", field: "Locatoin" },
//   { label: "Education", field: "educationInformation.highestDegree" },
//   { label: "Status", field: "status" },
// ];
export const USER_TABLE_DATA_COLUMNS = [
  { label: "Full Name", field: "fullName" },
  { label: "Date of Birth", field: "dob" },
  { label: "Email", field: "email" },
  { label: "Phone", field: "phoneNumber" },
  { label: "Gender", field: "gender" },
  { label: "Marital Status", field: "maritalStatus" },
  { label: "Education", field: "education" },
  { label: "Status", field: "status" },
];

// rows: [
//   {
//     profile: "Jon Snow",
//     Gender: "Male",
//     Age: "29",
//     maritalStatus: "Single",
//     subscription: "Premium",
//     Locatoin: "pakistan",
//     status: "active",
//     Education: "Master's Degree",
//   },
// ...Array(5).fill({
//   profile: "Jon Snow",
//   Gender: "Male",
//   Age: "29",
//   maritalStatus: "Single",
//   subscription: "Premium",
//   Locatoin: "pakistan",
//   status: "active",
//   Education: "Master's Degree",
// }),
// ],

export const DATA_SENT = [
  {
    categoryTitle: "Date Sent",
    title: "6/23/2023",
  },
  {
    categoryTitle: "category",
    title: "Misuse",
  },
  {
    categoryTitle: "Content Type",
    title: "User Profile",
  },
];

//PERSONAL INFORMATION
export const PROFESSION = [
  "Software Developer",
  "Data Scientist",
  "Doctor",
  "Engineer",
  "Teacher",
  "Nurse",
  "Architect",
  "Lawyer",
  "Accountant",
  "Chef",
  "Photographer",
  "Designer",
  "Entrepreneur",
  "Researcher",
  "Scientist",
  "Consultant",
  "Project Manager",
  "Marketer",
  "Civil Servant",
  "Psychologist",
  "Pharmacist",
  "Veterinarian",
  "Journalist",
  "Social Worker",
  "Human Resources Specialist",
  "Web Developer",
  "Graphic Designer",
  "Content Creator",
  "Event Planner",
  "Sales Representative",
  "Fashion Designer",
  "Public Relations Specialist",
  "Real Estate Agent",
  "Fitness Trainer",
  "Musician",
  "Artist",
  "Architect",
  "Teacher’s Assistant",
  "Construction Manager",
  "Speech Therapist",
  "Interior Designer",
  "Financial Analyst",
  "IT Specialist",
  "Marketing Manager",
  "Nurse Practitioner",
  "Biotechnologist",
  "Electrician",
  "Lawyer (Corporate)",
  "Research Scientist",
  "Copywriter",
];
export const RELOCATE = [
  "None",
  "Locally",
  "Regionally",
  "Nationally",
  "InterNationally",
];
export const LOOKING_TO_MARRY = [
  "As soon as possilbe",
  "This year",
  "Next year",
  "UNsure",
];
export const CURRENT_INCOME = [
  "Upto 15k",
  "15k to 25k",
  "25k to 50k",
  "over 50k",
  "Prefer not to say",
];
export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
export const PAKISTAN_STATES = [
  "Azad Jammu and Kashmir",
  "Balochistan",
  "Federally Administered Tribal Areas (FATA)",
  "Gilgit-Baltistan",
  "Khyber Pakhtunkhwa",
  "Punjab",
  "Sindh",
];
export const HAS_CHILDREN = [
  "Yes",
  "No",
  "I have one",
  "I have two ",
  "I have three",
  "I have more than three",
];
export const LIVING_ARRANGEMENTS = [
  "I live alone",
  "I live with friends",
  "I live with family",
  "Other",
];
export const WANTS_CHILDREN = ["Yes", "No", "Unsure"];
export const MARITAL_STATUS = [
  // "Never married",
  // "Legally separated",
  // "Divorced",
  // "Widowed",
  // "Annulled",
  "Single",
  "Married",
  "Divorced",
  "Widowed",
];

//APPEARANCE
export const HEIGHTS_OPTIONS = [
  "4'10\"",
  "4'11\"",
  "5'0\"",
  "5'1\"",
  "5'2\"",
  "5'3\"",
  "5'4\"",
  "5'5\"",
  "5'6\"",
  "5'7\"",
  "5'8\"",
  "5'9\"",
  "5'10\"",
  "5'11\"",
  "6'0\"",
  "6'1\"",
  "6'2\"",
  "6'3\"",
  "6'4\"",
  "6'5\"",
];
export const BUILD_OPTIONS = [
  "Petite",
  "Slim",
  "Athletic",
  "Medium",
  "Muscular",
  "Large",
];
export const EYE_COLORS = [
  "Brown",
  "Blue",
  "Green",
  "Hazel",
  "Gray",
  "Amber",
  "Red",
  "Violet",
  "Heterochromia",
];
export const HAIR_COLORS = [
  "Black",
  "Brown",
  "Blonde",
  "Red",
  "Auburn",
  "Gray",
  "White",
  "Blue",
  "Green",
  "Pink",
  "Purple",
  "Silver",
  "Ombre",
];

export const DISABILITIES = [
  "Visual Impairment",
  "Hearing Impairment",
  "Speech Impairment",
  "Physical Disability",
  "Intellectual Disability",
  "Autism Spectrum Disorder",
  "Down Syndrome",
  "Cerebral Palsy",
  "Multiple Sclerosis",
  "Parkinson’s Disease",
  "Spinal Cord Injury",
  "Muscular Dystrophy",
  "Epilepsy",
  "Mental Health Disorder",
  "Chronic Pain",
  "Learning Disability",
  "ADHD",
  "Alzheimer’s Disease",
  "Amputation",
  "Dwarfism",
];
export const SMOKE_OPTIONS = [
  "Any",
  "Yes",
  "No",
  "Sometimes",
  "I've stopped smoking",
];

//Education
export const EDUCATION_LEVEL = [
  "High School",
  "College",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate (PhD)",
];
export const PROFESSIONS = [
  "Software Developer",
  "Data Scientist",
  "Doctor",
  "Engineer",
  "Teacher",
  "Nurse",
  "Architect",
  "Lawyer",
  "Accountant",
  "Chef",
  "Photographer",
  "Designer",
  "Entrepreneur",
  "Researcher",
  "Scientist",
  "Consultant",
  "Project Manager",
  "Marketer",
  "Civil Servant",
  "Psychologist",
  "Pharmacist",
  "Veterinarian",
  "Journalist",
  "Social Worker",
  "Human Resources Specialist",
  "Web Developer",
  "Graphic Designer",
  "Content Creator",
  "Event Planner",
  "Sales Representative",
  "Fashion Designer",
  "Public Relations Specialist",
  "Real Estate Agent",
  "Fitness Trainer",
  "Musician",
  "Artist",
  "Architect",
  "Teacher’s Assistant",
  "Construction Manager",
  "Speech Therapist",
  "Interior Designer",
  "Financial Analyst",
  "IT Specialist",
  "Marketing Manager",
  "Nurse Practitioner",
  "Biotechnologist",
  "Electrician",
  "Lawyer (Corporate)",
  "Research Scientist",
  "Copywriter",
];

//languages
export const LANGUAGES = [
  "English",
  "Mandarin Chinese",
  "Spanish",
  "Hindi",
  "Arabic",
  "French",
  "Bengali",
  "Russian",
  "Portuguese",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "Swahili",
  "Turkish",
  "Korean",
  "Italian",
  "Persian (Farsi)",
  "Thai",
  "Polish",
];

//Religion
export const RELIGION_OPTIONS = [
  "Very religious",
  "Religious",
  "Some what religious",
  "Not religious",
  "Prefer not to say",
];
export const SEC_DATA = [
  "Just Muslim",
  "Shia",
  "Suni",
  "Other - Please ask me",
];
export const PREFER_HIJAB = [
  "Yes Hijab",
  "Yes Niqab",
  "No",
  "Prefer not to say",
];
export const KEEPS_HALAL = [
  "I always keep halal",
  "Usually keep halal",
  "I keep halal at home only",
  "I don't keep halal",
];
export const PERFROMS_SALAAH = ["Always", "Usually", "Sometimes", "Never"];
export const BEARD = ["Any", "Yes", "No", "Prefer not to say"];

export const APP_INSTALL_DATA = [
  { name: "Jan", Android: 4000, iOS: 2400, amt: 12000 },
  { name: "Feb", Android: 3000, iOS: 1398, amt: 25000 },
  { name: "Mar", Android: 2000, iOS: 9800, amt: 60000 },
  { name: "Apr", Android: 2780, iOS: 3908, amt: 45000 },
  { name: "May", Android: 1890, iOS: 4800, amt: 18000 },
  { name: "Jun", Android: 2390, iOS: 3800, amt: 30000 },
  { name: "Jul", Android: 3490, iOS: 4300, amt: 52000 },
  { name: "Aug", Android: 4200, iOS: 5100, amt: 34000 },
  { name: "Sep", Android: 3100, iOS: 2900, amt: 27000 },
  { name: "Oct", Android: 3700, iOS: 4600, amt: 41000 },
  { name: "Nov", Android: 4500, iOS: 5200, amt: 56000 },
  { name: "Dec", Android: 5000, iOS: 6000, amt: 60000 },
];
export const DATAING_USER_DATA = [
  { month: "Jan", totalUsers: 1200, activeUsers: 900, inactiveUsers: 300 },
  { month: "Feb", totalUsers: 1800, activeUsers: 1400, inactiveUsers: 400 },
  { month: "Mar", totalUsers: 2500, activeUsers: 2000, inactiveUsers: 500 },
  { month: "Apr", totalUsers: 3100, activeUsers: 2400, inactiveUsers: 700 },
  { month: "May", totalUsers: 4000, activeUsers: 3100, inactiveUsers: 900 },
  { month: "Jun", totalUsers: 5000, activeUsers: 3900, inactiveUsers: 1100 },
  { month: "Jul", totalUsers: 6300, activeUsers: 5000, inactiveUsers: 1300 },
  { month: "Aug", totalUsers: 7200, activeUsers: 5800, inactiveUsers: 1400 },
  { month: "Sep", totalUsers: 8100, activeUsers: 6400, inactiveUsers: 1700 },
  { month: "Oct", totalUsers: 9200, activeUsers: 7200, inactiveUsers: 2000 },
  { month: "Nov", totalUsers: 10500, activeUsers: 8300, inactiveUsers: 2200 },
  { month: "Dec", totalUsers: 12000, activeUsers: 9500, inactiveUsers: 2500 },
];
export const GENDER = ["male", "female"];

export const sections = [
  {
    title: "Personal Information",
    data: {
      "My Citizenship": "Pakistani",
      "Country of Origin": "Pakistan",
      "Willing to Relocate?": "Internationally",
      "I am Education to Marry": "As soon as possible",
      "My Income": "Prefer not to say",
      "Marital Status": "Never married",
      "Would I like to have Children?": "Yes",
      "Do I have children?": "No",
      "My Living Arrangements?": "I Live With Family",
      Country: "Pakistan",
      "County/State": "Gujrat",
      Distance: "213 miles",
    },
  },
  {
    title: "Appearance",
    data: {
      "My Height": "1.55m (5'1\")",
      "My Build": "Slim",
      "My Hair Colour": "Black",
      "Colour of My Eyes": "Brown",
      "Do I Smoke?": "No",
      "Do I Have Any Disabilities?": "No",
    },
  },
  {
    title: "Education",
    data: {
      "My Education Level": "Bachelors degree",
      "Subject I Studied": "Commerce",
    },
  },
  {
    title: "Language",
    data: {
      "My First Language": "Urdu",
      "My Second Language": "Punjabi",
    },
  },
  {
    title: "Work",
    data: {
      "My Profession": "Prefer not to say",
      "My Job Title": "Not working",
    },
  },
  {
    title: "Religion",
    data: {
      Religiousness: "Religious",
      "My Sect": "Sunni",
      "Hijab/Niqab ": "Yes Hijab",
      " Beard": "Yes",
      "Are You a Revert? ": "N0",
      "Do You Keep Halal?": "I Always Keep Halal",
      "Do You Perform Salaah?": "Always",
    },
  },
];

// export const ADMIN_ROLE = ["super_admin", "moderator", "support", "editor"];
export const ADMIN_ROLE = ["moderator", "support", "editor"];
export const GenderTypes = ["male", "female"];
export const SoftSkills: string[] = [
  "Communication",
  "Teamwork",
  "Problem-Solving",
  "Time Management",
  "Adaptability",
  "Creativity",
  "Leadership",
  "Critical Thinking",
  "Work Ethic",
  "Emotional Intelligence",
  "Decision Making",
  "Conflict Resolution",
  "Negotiation",
  "Active Listening",
  "Collaboration",
  "Flexibility",
  "Interpersonal Skills",
  "Attention to Detail",
  "Resilience",
  "Self-Motivation",
];

export const TechnicalSkills: string[] = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "Redux",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Git",
  "GitHub",
  "REST API",
  "GraphQL",
  "MongoDB",
  "Firebase",
  "Appwrite",
  "SQL",
  "PostgreSQL",
  "Docker",
  "Kubernetes",
  "AWS",
  "Google Cloud",
  "CI/CD",
  "Testing (Jest, Cypress)",
  "Data Structures",
  "Algorithms",
];
export const Religions: string[] = [
  "Islam",
  "Christianity",
  "Hinduism",
  "Buddhism",
  "Judaism",
  "Sikhism",
  "Baháʼí",
  "Jainism",
  "Shinto",
  "Taoism",
  "Zoroastrianism",
  "Atheism",
  "Agnosticism",
  "Other",
];


export const MEMBER_ROLE = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "UI/UX Designer",
  "Web Designer",
  "Graphic Designer",
  "Project Manager",
  "Product Manager",
  "Quality Assurance (QA) Engineer",
  "DevOps Engineer",
  "Content Writer",
  "SEO Specialist",
  "Digital Marketer",
  "Social Media Manager",
  "Sales Executive",
  "Client Success Manager",
  "Business Analyst",
  "Mobile App Developer",
  "Software Engineer",
  "Technical Lead"
];
